PruebaFinal/PruebaFinal/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, PasswordResetView, logout_then_login,\
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('admin/', admin.site.urls),
    path('encargado/', include (('apps.encargado.urls', 'encargado'), namespace='encargado')),
    path('task/', include (('apps.task.urls', 'task'), namespace='task')),
    path('accounts/login/', LoginView.as_view(template_name='inde.html'), name="login"),
]

PruebaFinal/apps/encargado/urls.py
from django.conf.urls import url, include
from django.urls import path
from apps.encargado.views import index, EncargadoList, EncargadoCreate, EncargadoUpdate, EncargadoDelete
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', index, name='encargado_principal'),
    path('nuevo/', login_required(EncargadoCreate.as_view()), name='encargado_create'),
    path('listar/', login_required(EncargadoList.as_view()), name='encargado_list'),
    path('editar/<int:pk>/', login_required(EncargadoUpdate.as_view()), name='encargado_edit'),
    path('eliminar/<int:pk>/', login_required(EncargadoDelete.as_view()), name='encargado_delete'),
]

PruebaFinal/apps/task/urls.py
from django.conf.urls import url, include
from django.urls import path
from apps.task.views import Task, TaskList, TaskCreate, TaskUpdate, TaskDelete, TaskListTar
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('nuevo/', login_required(TaskCreate.as_view()), name='task_create'),
    path('listar/', login_required(TaskList.as_view()), name='task_list'),
    path('listarTask/', login_required(TaskListTar.as_view()), name='task_list_tar'),
    path('editar/<int:pk>)/', login_required(TaskUpdate.as_view()), name='task_edit'),
    path('eliminar/<int:pk>)/', login_required(TaskDelete.as_view()), name='task_delete'),
]

PruebaFinal/apps/usuario/urls.py
from django.conf.urls import url
from django.urls import path
from apps.usuario.views import RegistroUsuario, listadousuarios

urlpatterns = [
    path('registrar/', RegistroUsuario.as_view(), name="registrar"),
    path('listado/', listadousuarios, name="listado")
]

PruebaFinal/apps/encargado/models.py
from django.db import models

# Create your models here.

class Encargado(models.Model):
    nombre_encargado = models.CharField(max_length=50)
    apellido_encargado = models.CharField(max_length=50)
    genero = models.CharField(max_length=10)
    nombre_usuario = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField()

    def __str__(self):
        return '{}'.format(self.nombre_encargado)

PruebaFinal/apps/task/models.py
from django.db import models

from apps.encargado.models import Encargado

# Create your models here.

class Task(models.Model):
    titulo_task = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=100)
    fecha_entrega = models.DateField()
    encargado = models.ForeignKey(Encargado, null=True, blank=True, on_delete=models.CASCADE)

PruebaFinal/apps/usuario/models.py
from django.db import models

# Create your models here.

PruebaFinal/apps/encargado/forms.py
from django import forms

from apps.encargado.models import Encargado

class EncargadoForm (forms.ModelForm):
    
    class Meta:
        model = Encargado

        fields = [
            'nombre_encargado',
            'apellido_encargado',
            'genero',
            'nombre_usuario',
            'fecha_nacimiento',
        ]   
        label = {
            'nombre_encargado':'Nombre Encargado',
            'apellido_encargado':'Apellido Encargado',
            'genero':'Genero',
            'nombre_usuario':'Nombre Usuario',
            'fecha_nacimiento':'Fecha Nacimiento',
        }
        widgets = {
            'nombre_encargado': forms.TextInput(attrs={'class':'form-control'}),
            'apellido_encargado': forms.TextInput(attrs={'class':'form-control'}),
            'genero': forms.TextInput(attrs={'class':'form-control'}),
            'nombre_usuario': forms.TextInput(attrs={'class':'form-control'}),
            'fecha_nacimiento': forms.TextInput(attrs={'class':'form-control'}),
        }

PruebaFinal/apps/task/forms.py
from django import forms

from apps.task.models import Task

class TaskForm (forms.ModelForm):
    
    class Meta:
        model = Task

        fields = [
            'titulo_task',
            'descripcion',
            'fecha_entrega',
            'encargado',
        ]
        label = {
            'titulo_task': 'Titulo Task',
            'descripcion': 'Descripcion',
            'fecha_entrega': 'Fecha Entrega',
            'encargado': 'Encargado',
        }
        widgets = {
            'titulo_task': forms.TextInput(attrs={'class':'form-control'}),
            'descripcion': forms.TextInput(attrs={'class':'form-control'}),
            'fecha_entrega': forms.TextInput(attrs={'class':'form-control'}),
            'encargado': forms.Select(attrs={'class': 'form-control'})
        }

PruebaFinal/apps/usuario/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistroForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]
        labels = {
            'username': 'Nombre de usuario',
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'email': 'Correo',
        }

PruebaFinal/apps/encargado/views.py
from django.shortcuts import render, redirect
from apps.encargado.forms import EncargadoForm
from apps.encargado.models import Encargado
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.

def index(request):
    return render (request, 'encargado/index.html')

class EncargadoList(ListView):
    model = Encargado
    template_name = 'encargado/encargado_list.html'
    paginate_by = 5

class EncargadoCreate(CreateView):
    model = Encargado
    form_class = EncargadoForm
    template_name = 'encargado/encargado_form.html'
    success_url = reverse_lazy('encargado:encargado_list')

class EncargadoUpdate(UpdateView):
    model = Encargado
    form_class = EncargadoForm
    template_name = 'encargado/encargado_form.html'
    success_url = reverse_lazy('encargado:encargado_list')

class EncargadoDelete(DeleteView):
    model = Encargado
    template_name = 'encargado/encargado_delete.html'
    success_url = reverse_lazy('encargado:encargado_list')

PruebaFinal/apps/task/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.task.forms import TaskForm
from apps.task.models import Task

class TaskList(ListView):
    model = Task
    template_name = 'task/task_list.html'
    paginate_by = 5

class TaskListTar(ListView):
    model = Task
    template_name = 'task/task_tar_list.html'

class TaskCreate(CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'task/task_form.html'
    success_url = reverse_lazy('task:task_list')

class TaskUpdate(UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'task/task_form.html'
    success_url = reverse_lazy('task:task_list')

class TaskDelete(DeleteView):
    model = Task
    template_name = 'task/task_delete.html'
    success_url = reverse_lazy('task:task_list')

PruebaFinal/apps/usuario/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy
from apps.usuario.forms import RegistroForm
from django.contrib import messages
from django.core import serializers
from django.http import HttpResponse

# Create your views here.
def listadousuarios(request):
    lista = serializers.serialize('json', User.objects.all(), fields=['username', 'first_name', 'email'])
    return HttpResponse(lista, content_type='application/json')
    
class RegistroUsuario(CreateView):
    model = User
    template_name = 'usuario/registrar.html'
    form_class = RegistroForm
    success_url = reverse_lazy('encargado:encargado_principal')

PruebaFinal/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href=" {% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'font/fontello-dbf9097f/css/fontello.css' %}">
    <link rel="stylesheet" href="{% static 'font/fontello-d027f459/css/fontello.css' %}">
    <link rel="stylesheet" href="{% static 'font/fontello-31d05a21/css/fontello.css' %}">
    {% block title %}<title>Document</title>{% endblock %}
</head>

<body>
    {% block header %}
    <!--++++++++++++++++++++Navbar+++++++++++++++++++++++++++++++-->
    <div class="cont-up" id="rojo">
        <div class="main-navbar">
            <i class="fa fa-plane icon-paper-plane-empty i-nav"></i>
            <div class="main-navbar__head-one" id="up">
                <div class="div">
                        <a class="btn" style="background-color:#1b9696; color: white;" href="{% url 'encargado:encargado_principal' %}">Inicio</a>
                        <a class="btn" style="background-color:#1b9696; color: white;" href="{% url 'encargado:encargado_list' %}">Encargado</a>
                        <a class="btn" style="background-color:#1b9696; color: white;" href="{% url 'task:task_list' %}">Task</a>
                        <a class="btn" style="background-color:#1b9696; color: white;" href="{% url 'task:task_list_tar' %}">Tarjetas Task</a>
                </div>
            </div>
            <div class="main-navbar__head-two" id="up">
                <div class="main-navbar__head-one__one">
                    <i class="fa fa-bell icon-bell-alt head-two__i-one__one"></i>
                </div>
                <div>
                    <i class="fa fa-user icon-user-circle head-two__i"></i>
                </div>
                <div class="main-navbar__head-one__two">
                    <i class="fa fa-cog icon-cog head-two__i-one__three"></i>
                    <i class="fa fa-down-dir icon-sort-down head-two__i-one__two"></i>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

       {% block left %}
    <div class="cont-left" id="rojo">
        <div class="cont-left__one">
            <i class="fa fa-home icon-home i-nav-left"></i>
        </div>
        <div class="cont-left__one">
            <i class="fa fa-book icon-book-1 i-nav-left__one"></i>
        </div>
        <div class="cont-left__one">
            <i class="fa fa-calendar icon-calendar-empty i-nav-left__one"></i>
        </div>
        <div class="cont-left__one">
            <i class="fa fa-docs icon-docs i-nav-left__one"></i>
        </div>
        <div class="cont-left__one">
            <i class="fa fa-users icon-users i-nav-left__one"></i>
        </div>
        <div class="cont-left__one">
            <i class="fa fa-logout icon-login i-nav-left__one"></i>
        </div>
    </div>
    {% endblock %}


    {% block content %}
    <img src="{% static 'images/edoo_logo.png' %}" style="margin-left: 25%;margin-top: 20%; width:40rem">
    {% endblock %}

    {% block footer %}

    {% endblock %}


</body>

</html>

PruebaFinal/templates/base/base2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href=" {% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos2.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'font/fontello-dbf9097f/css/fontello.css' %}">
    <link rel="stylesheet" href="{% static 'font/fontello-d027f459/css/fontello.css' %}">
    <link rel="stylesheet" href="{% static 'font/fontello-31d05a21/css/fontello.css' %}">
    {% block title %}<title>Tarjetas</title>{% endblock %}
</head>

<body>
    {% block header %}
    <!--++++++++++++++++++++Navbar+++++++++++++++++++++++++++++++-->
    <div class="cont-up" id="rojo">
        <div class="main-navbar">
            <i class="fa fa-plane icon-paper-plane-empty i-nav"></i>
            <div class="main-navbar__head-one" id="up">
                <div class="div">
                    <a class="btn" style="background-color:#1b9696; color: white;"
                        href="{% url 'encargado:encargado_list' %}">Encargado</a>
                    <a class="btn" style="background-color:#1b9696; color: white;"
                        href="{% url 'task:task_list' %}">Task</a>
                    <a class="btn" style="background-color:#1b9696; color: white;"
                        href="{% url 'task:task_list_tar' %}">Tarjetas Task</a>
                </div>
            </div>
            <div class="main-navbar__head-two" id="up">
                <div class="main-navbar__head-one__one">
                    <i class="fa fa-bell icon-bell-alt head-two__i-one__one"></i>
                </div>
                <div>
                    <i class="fa fa-user icon-user-circle head-two__i"></i>
                </div>
                <div class="main-navbar__head-one__two">
                    <i class="fa fa-cog icon-cog head-two__i-one__three"></i>
                    <i class="fa fa-down-dir icon-sort-down head-two__i-one__two"></i>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

    {% block left %}
    <div class="cont-left" id="rojo">
        <div class="cont-left__one">
            <i class="fa fa-home icon-home i-nav-left"></i>
        </div>
        <div class="cont-left__one">
            <i class="fa fa-book icon-book-1 i-nav-left__one"></i>
        </div>
        <div class="cont-left__one">
            <i class="fa fa-calendar icon-calendar-empty i-nav-left__one"></i>
        </div>
        <div class="cont-left__one">
            <i class="fa fa-docs icon-docs i-nav-left__one"></i>
        </div>
        <div class="cont-left__one">
            <i class="fa fa-users icon-users i-nav-left__one"></i>
        </div>
        <div class="cont-left__one">
            <i class="fa fa-logout icon-login i-nav-left__one"></i>
        </div>
    </div>
    {% endblock %}
    {% block medio %}
    <div class="body__cont-center" id="cuerpo">
        <div class="body__cont-center__one" id="blanco">
            <i class="fa fa-book icon-book-1 i-nav-left__book"></i>
            <label class="label-titulos">Tarjetas Task</label>
        </div>
        {% block card %}
        {% for task in object_list  %}
        <div class="container__Card-center" id="cuerpo">
            <div class="card" id="blanco">
                <div class="card__head" id="up">
                    <div class="card__head__one" id="rojo-f">
                        <label class="card__h1">{{task.titulo_task}}</label><br>
                        <p class="card__p">{{task.fecha_entrega}}</p>
                        <i class="fa fa-superscript icon-superscript card__icon__one"></i>
                    </div>
                </div>
                <div class="card__icon" id="rojo-ligth">
                    <div class="cont__icon-card-one">
                        <i class="fa fa-plane icon-paper-plane-empty i-nav-left__card"></i>
                    </div>
                    <div class="cont__icon-card-one">
                        <i class="fa fa-users icon-users i-nav-left__card"></i>
                    </div>
                    <div class="cont__icon-card-one">
                        <i class="fa fa-docs icon-docs i-nav-left__card"></i>
                    </div>
                    <div class="cont__icon-card-one">
                        <i class="fa fa-docs icon-docs i-nav-left__card"></i>
                    </div>
                </div>
                <div class="card__cont" id="blanco">
                    <p class="card__medio">{{task.descripcion}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endblock %}
        {% endblock %}

</body>

</html>

PruebaFinal/templates/encargado/encargado_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="post" class="form-group card" style="margin-left:30rem;margin-top:0; top:12rem;">
        {% csrf_token %}
        <h1 style="text-align:center;color:#1b9696;">¿Desea eliminar el registro {{ encargado.nombre_encargado }}?</h1>
        <button class="btn btn-danger" type="submit" style="margin: 0.5rem">Si, Eliminar</button>
        <a class="btn btn-success" style="margin: 0.5rem" href="{% url 'encargado:encargado_list' %}">Cancelar</a>
    </form>
{% endblock %}

PruebaFinal/templates/encargado/encargado_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post" class="form-group card" style="margin-left:30rem;margin-top:0; top:5rem;">
    {% csrf_token %}
    <h1 style="text-align:center;color:#1b9696; padding: 0.5rem">Encargado</h1>
    {{ form.as_p }}
    <button style="margin-top: 1rem;" class="btn btn-outline-info" type="submit">Guardar</button>
</form>
{% endblock %}

PruebaFinal/templates/encargado/encargado_list.html
{% extends 'base/base.html' %}

{% block content %}
<table class="table table-bordered">
    <div class="form-group">
        <h1 style="text-align:center; padding: 5rem 0 3rem 0; color: #1b9696;">Listado de Encargados</h1>
        <thead>
            <tr class="table-info h5">
                <td style="text-align: center">#</td>
                <td style="text-align: center">Nombre Encargado</td>
                <td style="text-align: center">Apellido Encargado</td>
                <td style="text-align: center">Genero</td>
                <td style="text-align: center">Nombre Usuario</td>
                <td style="text-align: center">Fecha Nacimiento</td>
                <td style="text-align: center">Acciones</td>
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
            {% for encargado in object_list %}
            <tr>
                <td style="text-align: center; font-size: 1rem;">{{ encargado.id }}</td>
                <td style="text-align: center; font-size: 1rem;">{{ encargado.nombre_encargado }}</td>
                <td style="text-align: center; font-size: 1rem;">{{ encargado.apellido_encargado }}</td>
                <td style="text-align: center; font-size: 1rem;">{{ encargado.genero }}</td>
                <td style="text-align: center; font-size: 1rem;">{{ encargado.nombre_usuario }}</td>
                <td style="text-align: center; font-size: 1rem;">{{ encargado.fecha_nacimiento }}</td>
                <td>
                    <a class="btn btn-outline-primary" href="{% url 'encargado:encargado_edit' encargado.id %}">EDITAR</a>
                    <a class="btn btn-outline-danger" href="{% url 'encargado:encargado_delete' encargado.id %}">ELIMINAR</a>
                </td>
            </tr>
            {% endfor %}
            <a class="btn btn-outline-info" style="margin: 1rem; margin-left: 4rem;" href="{% url 'encargado:encargado_create'%}">AGREGAR ENCARGADO</a>
            {% else %}
            <h1 style="text-align: center">NO HAY ENCARGADOS PARA MOSTRAR</h1>
            <a class="btn btn-outline-info" style="margin: 1rem; margin-left: 4rem;" href="{% url 'encargado:encargado_create'%}">AGREGAR ENCARGADO</a>
            {% endif %}
        </tbody>
    </div>
</table>
<ul style="margin-top:3rem;">
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-success" style="margin-left: 1.5rem;" href="?page={{ page_obj.previous_page_number }}">Regresar</a>
        {% endif %}
    {% if page_obj.has_next %}
        <a class="btn btn-outline-success" style="margin-left: 1.5rem;" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
        {% endif %}
</ul>
{% endblock %}

PruebaFinal/templates/encargado/index.html
{% extends 'base/base.html' %}

PruebaFinal/templates/inde.html
{% extends 'base/base.html' %}

{% block header %}
<!--++++++++++++++++++++Navbar+++++++++++++++++++++++++++++++-->
<div class="cont-up" id="rojo">
    <div class="main-navbar">
        <i class="fa fa-plane icon-paper-plane-empty i-nav"></i>
        <div class="main-navbar__head-one" id="up">
            <div class="div">
                <a class="btn" style="background-color:#1b9696; color: white;"
                    href="{% url 'login' %}">Login</a>
            </div>
        </div>
        <div class="main-navbar__head-two" id="up">
            <div class="main-navbar__head-one__one">
                <i class="fa fa-bell icon-bell-alt head-two__i-one__one"></i>
            </div>
            <div>
                <i class="fa fa-user icon-user-circle head-two__i"></i>
            </div>
            <div class="main-navbar__head-one__two">
                <i class="fa fa-cog icon-cog head-two__i-one__three"></i>
                <i class="fa fa-down-dir icon-sort-down head-two__i-one__two"></i>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<form method="post" class="form-group card" style="margin-left:30rem;margin-top:0; top:5rem;">
    <h1 style="text-align:center;color:#1b9696; padding: 0.5rem">Iniciar Sesion</h1>
    {% csrf_token %}
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="username">Nombre de Usuario: admin</label>
                <input class="form-control" type="text" name="username">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="username">Password: admin</label>
                <input class="form-control" type="password" name="password">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input class="form-control" type="submit" value="ingresar">
            </div>
        </div>
    </div>
</form>
{% endblock %}

PruebaFinal/templates/task/task_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="post" class="form-group card" style="margin-left:30rem;margin-top:0; top:12rem;">
        {% csrf_token %}
        <h1 style="text-align:center;color:#1b9696;">¿Desea eliminar el registro {{ task.titulo_task }}?</h1>
        <button class="btn btn-danger" type="submit" style="margin: 0.5rem">Si, Eliminar</button>
        <a class="btn btn-success" style="margin: 0.5rem" href="{% url 'task:task_list' %}">Cancelar</a>
    </form>
{% endblock %}

PruebaFinal/templates/task/task_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post" class="form-group card" style="margin-left:30rem;margin-top:0; top:5rem;">
    {% csrf_token %}
    <h1 style="text-align:center;color:#1b9696; padding: 0.5rem">Task</h1>
    {{ form.as_p }}
    <button style="margin-top: 1rem;" class="btn btn-outline-info" type="submit">Guardar</button>
</form>
{% endblock %}

PruebaFinal/templates/task/task_list.html
{% extends 'base/base.html' %}

{% block content %}
<table class="table table-bordered">
    <div class="form-group">
        <h1 style="text-align:center; padding: 5rem 0 2rem 0; color: #1b9696;">Listado de Task</h1>
        <thead>
            <tr class="table-info h5">
                <td style="text-align: center">#</td>
                <td style="text-align: center">Titulo Task</td>
                <td style="text-align: center">Fecha Entrega</td>
                <td style="text-align: center">Encargado</td>
                <td style="text-align: center">Acciones</td>
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
            {% for task in object_list %}
            <tr>
                <td style="text-align: center; font-size: 1rem;">{{ task.id }}</td>
                <td style="text-align: center; font-size: 1rem;">{{ task.titulo_task }}</td>
                <td style="text-align: center; font-size: 1rem;">{{ task.fecha_entrega }}</td>
                <td style="text-align: center; font-size: 1rem;">{{ task.encargado }}</td>
                <td>
                    <a class="btn btn-outline-primary" href="{% url 'task:task_edit' task.id %}">EDITAR</a>
                    <a class="btn btn-outline-danger" href="{% url 'task:task_delete' task.id %}">ELIMINAR</a>
                </td>
            </tr>
            {% endfor %}
            <a class="btn btn-outline-info" style="margin: 1rem; margin-left: 5rem;" href="{% url 'task:task_create'%}">AGREGAR TASK</a>
            {% else %}
            <h1 style="text-align: center">NO HAY TASK PARA MOSTRAR</h1>
            <a class="btn btn-outline-info" style="margin: 1rem; margin-left: 5rem;" href="{% url 'task:task_create'%}">AGREGAR TASK</a>
            {% endif %}
        </tbody>
    </div>
</table>
<ul style="margin-top:3rem;">
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-success" href="?page={{ page_obj.previous_page_number }}">Regresar</a>
        {% endif %}
    {% if page_obj.has_next %}
        <a class="btn btn-outline-success" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
        {% endif %}
</ul>
{% endblock %}

PruebaFinal/templates/task/task_tar_list.html
{% extends 'base/base2.html' %}

{% block card %}
{% for task in object_list  %}
<div class="container__Card-center" id="cuerpo">
    <div class=" card" id="blanco">
        <div class="card__head" id="up">
            <div class="card__head__one" id="up">
                <label class="card__h1">{{task.titulo_task}}</label><br>
                <p class="card__p">Entrega: {{task.fecha_entrega}}</p>
                <i class="fa icon-snapchat-ghost card__icon__one"></i>
            </div>
        </div>
        <div class="card__icon" id="up">
            <div class="cont__icon-card-one">
                <i class="fa fa-plane icon-paper-plane-empty i-nav-left__card"></i>
            </div>
            <div class="cont__icon-card-one">
                <i class="fa fa-users icon-users i-nav-left__card"></i>
            </div>
            <div class="cont__icon-card-one">
                <i class="fa fa-docs icon-docs i-nav-left__card"></i>
            </div>
            <div class="cont__icon-card-one">
                <i class="fa fa-docs icon-docs i-nav-left__card"></i>
            </div>
        </div>
        <div class="card__cont" id="blanco">
            <p class="card__medio">{{task.descripcion}}</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}